# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.1
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pantheon
  name: pantheon
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - exec java $JAVA_OPTS -jar org.apache.sling.starter.jar $SLING_OPTS
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pantheon
    - name: JAVA_HOME
      value: /usr/lib/jvm/java-1.8-openjdk/jre
    - name: JAVA_OPTS
      value: -Xmx512m
    - name: SLING_OPTS
      value: -Dsling.run.modes=oak_mongo -Doak.mongo.uri=mongodb://localhost:27017
    - name: LANG
      value: C.UTF-8
    image: docker.io/apache/sling@sha256:3a22d3eb91ccaa267333eaa605d2fae7d38b44f4db77d64e93cded5f5c4610ce
    name: sling
    ports:
    - containerPort: 5005
      hostPort: 5005
      protocol: TCP
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /opt/sling/
  - command:
    - mongod
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pantheon
    image: docker.io/library/mongo:4.4.4
    name: slingmongo
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
  - name: pantheon-app
    image: localhost/pantheon:0.1.1
    env:
    - name: KARAF_DEBUG
      value: true
    - name: REPOSITORY
      value: sling/repository
    - name: MONGO_DB
      value: sling
    - name: MONGO_DB_URI
      value: "mongodb://localhost:27017"
    - name: MONGO_DB_REPLICA
      value: "mongodb://localhost:27017"
    - name: SYNC_SERVICE_URL
      value: "http://localhost:9666"
    resources: {}
    command: 
    - /opt/pantheon-karaf-dist/bin/karaf
    - run
    ports:
    - containerPort: 8181 
      hostPort:  8181
      protocol: TCP
  - name: git2pantheon
    image: localhost/git2pantheon:0.1.1
    ports:
    - containerPort: 9666
      hostPort:  9666
      protocol: TCP
status: {}

